# Generated by Django 5.1.5 on 2025-05-10 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('special_instructions', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
    ]
