# Generated by Django 5.1.5 on 2025-03-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveravailability',
            name='service_areas',
            field=models.ManyToManyField(to='Provider.servicearea'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver'),
        ),
    ]
