# Generated by Django 5.1.5 on 2025-05-10 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='provider',
            field=models.ForeignKey(help_text='Service provider this driver works for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='Provider.serviceprovider'),
        ),
    ]
