# Generated by Django 5.1.5 on 2025-05-10 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0002_initial'),
        ('Provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account associated with this driver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='Driver.driver'),
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='service_areas',
            field=models.ManyToManyField(to='Provider.servicearea'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Driver.driver'),
        ),
        migrations.AddField(
            model_name='driverinfringement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infringements', to='Driver.driver'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['provider'], name='driver_provide_c9ef91_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='driver_status_8b0d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_expiry_date'], name='driver_license_2754db_idx'),
        ),
    ]
