# Generated by Django 5.1.5 on 2025-05-10 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('request_update', 'Request Update'), ('payment', 'Payment Notification'), ('bid', 'Bid Notification'), ('message', 'New Message'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
