# Generated by Django 5.2.1 on 2025-05-13 22:23

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('transit', 'Goods in Transit'), ('cmr', 'CMR Insurance'), ('liability', 'Public Liability')], max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('policy_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
                'db_table': 'insurance_policy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('is_primary', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'db_table': 'service_area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('limited', 'Limited Company'), ('sole_trader', 'Sole Trader'), ('partnership', 'Partnership')], max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('company_reg_number', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Alphanumeric characters only')])),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('business_description', models.TextField(blank=True, max_length=2000)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='service_providers/services/%Y/%m/')),
                ('base_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Primary service location coordinates', null=True, srid=4326)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('accepts_instant_bookings', models.BooleanField(default=True)),
                ('service_radius_km', models.PositiveIntegerField(default=50, help_text='Maximum service radius from base location (km)')),
                ('minimum_job_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('premium', 'Premium Verified')], default='unverified', max_length=20)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'db_table': 'service_provider',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WatchedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_watching', models.DateTimeField(default=django.utils.timezone.now)),
                ('notify', models.BooleanField(default=True)),
                ('notification_preferences', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Watched Job',
                'verbose_name_plural': 'Watched Jobs',
                'db_table': 'provider_watched_job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='Job.job')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'db_table': 'provider_saved_job',
                'managed': True,
            },
        ),
    ]
