# Generated by Django 5.1.5 on 2025-05-10 23:53

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job', '0003_initial'),
        ('Payment', '0003_initial'),
        ('Provider', '0001_initial'),
        ('Services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='insurance_policies',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='Provider.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='providers', to='Payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_categories',
            field=models.ManyToManyField(related_name='providers', to='Services.servicecategory', verbose_name='Service Categories'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='specializations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_specialization': True}, related_name='specializing_providers', to='Services.servicecategory', verbose_name='Specializations'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_insurance_policies', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='watchedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='Job.job'),
        ),
        migrations.AddField(
            model_name='watchedjob',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('job', 'provider')},
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['verification_status'], name='service_pro_verific_2de249_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=django.contrib.postgres.indexes.GistIndex(fields=['base_location'], name='service_pro_base_lo_1c15f5_gist'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=django.contrib.postgres.indexes.GistIndex(fields=['area'], name='service_are_area_dc0139_gist'),
        ),
        migrations.AlterUniqueTogether(
            name='watchedjob',
            unique_together={('job', 'provider')},
        ),
    ]
