# Generated by Django 5.1.5 on 2025-03-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bidding', '0002_initial'),
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Request.request'),
        ),
    ]
