# Generated by Django 5.2.1 on 2025-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bidding', '0002_initial'),
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Provider.serviceprovider'),
        ),
    ]
