# Generated by Django 5.1.5 on 2025-05-10 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('stop', 'Intermediate Stop')], max_length=20)),
                ('address', models.TextField()),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('floor', models.IntegerField(default=0)),
                ('has_elevator', models.BooleanField(default=False)),
                ('parking_info', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('estimated_time', models.TimeField(blank=True, help_text='Estimated time for this stop in HH:MM format', null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('completed_time', models.TimeField(blank=True, null=True)),
                ('property_type', models.CharField(default='house', max_length=50)),
                ('number_of_rooms', models.IntegerField(blank=True, default=1, null=True)),
                ('number_of_floors', models.IntegerField(blank=True, default=1, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('residential_moving', 'Residential Moving'), ('office_relocation', 'Office Relocation'), ('piano_moving', 'Piano Moving'), ('antique_moving', 'Antique Moving'), ('storage_services', 'Storage Services'), ('packing_services', 'Packing Services'), ('vehicle_transportation', 'Vehicle Transportation'), ('international_moving', 'International Moving'), ('furniture_assembly', 'Furniture Assembly'), ('fragile_items', 'Fragile Items'), ('artwork_moving', 'Artwork Moving'), ('industrial_equipment', 'Industrial Equipment'), ('electronics', 'Electronics'), ('appliances', 'Appliances'), ('boxes_parcels', 'Boxes/Parcels')], max_length=50, null=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Journey Stop',
                'verbose_name_plural': 'Journey Stops',
                'db_table': 'journey_stop',
                'ordering': ['sequence'],
                'managed': True,
            },
        ),
    ]
