# Generated by Django 5.1.5 on 2025-03-16 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0002_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('insurance_required', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('special_instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions', models.JSONField()),
                ('special_instructions', models.TextField(blank=True)),
                ('photos', models.JSONField(null=True)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropoffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.location')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('biddable', 'Biddable'), ('instant', 'Instant'), ('journey', 'Journey')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('bidding', 'Bidding in Progress'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('express', 'Express'), ('same_day', 'Same Day')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_pickup_date', models.DateField()),
                ('preferred_pickup_time_window', models.JSONField()),
                ('estimated_completion_time', models.DateTimeField(null=True)),
                ('items_description', models.TextField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions', models.JSONField()),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_factors', models.JSONField(null=True)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('insurance_required', models.BooleanField(default=False)),
                ('insurance_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_time', models.DateTimeField(null=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('route_optimization_data', models.JSONField(null=True)),
                ('weather_conditions', models.JSONField(null=True)),
                ('estimated_fuel_consumption', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('carbon_footprint', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('service_level', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('premium', 'Premium')], max_length=20)),
                ('estimated_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('route_waypoints', models.JSONField(null=True)),
                ('loading_time', models.DurationField(null=True)),
                ('unloading_time', models.DurationField(null=True)),
                ('price_breakdown', models.JSONField(null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Driver.driver')),
                ('dropoff_locations', models.ManyToManyField(related_name='dropoff_requests', through='Request.DropoffSchedule', to='Location.location')),
                ('pickup_locations', models.ManyToManyField(related_name='pickup_requests', through='Request.PickupSchedule', to='Location.location')),
            ],
        ),
    ]
