# Generated by Django 5.1.5 on 2025-03-16 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickupschedule',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request.request'),
        ),
        migrations.AddField(
            model_name='dropoffschedule',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request.request'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Request.itemcategory'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Request.request'),
        ),
    ]
