# Generated by Django 5.2.1 on 2025-05-13 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('insurance_required', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('special_instructions', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=100)),
                ('image', models.URLField(blank=True, help_text='URL to category image')),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
                ('tab_color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'item_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommonItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('fragile', models.BooleanField(default=False)),
                ('needs_disassembly', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
                ('tab_color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
                ('image', models.URLField(blank=True, help_text='URL to item image')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.itemcategory')),
            ],
            options={
                'verbose_name': 'Common Item',
                'verbose_name_plural': 'Common Items',
                'db_table': 'common_item',
                'managed': True,
            },
        ),
    ]
