# Generated by Django 5.2.1 on 2025-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('location', 'Location Update'), ('status', 'Status Update'), ('delay', 'Delay Notification'), ('completion', 'Completion Update')], max_length=20)),
                ('location', models.JSONField(null=True)),
                ('status_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delay', models.DurationField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='Request.request')),
            ],
            options={
                'db_table': 'tracking_update',
                'managed': True,
            },
        ),
    ]
